modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
authors = "${mod_authors}" #optional
description = '''${mod_description}'''

[[mixins]]
config = "moonstone.mixins.json"

[[dependencies.moonstone]]
modId="neoforge"
type="required"
versionRange="[21.0.28-beta,)"
ordering="NONE"
side="BOTH"
[[dependencies.moonstone]]
modId="minecraft"
type="required"
versionRange="[1.21, 1.22)"
ordering="NONE"
side="BOTH"